from constants import Type
semantic_cube = {
    Type.INT: {
        Type.INT:    {
            "+":       Type.INT,  
            "-":      Type.INT,     
            "*":      Type.INT,    
            "/":     Type.FLOAT,  
            "==":     Type.INT, 
            "GREATER":    Type.INT,   
            "LESS":       Type.INT,    
            "LESS_EQ":    Type.INT,    
            "GREATER_EQ": Type.INT, 
            "IS_EQUAL":   Type.INT,  
            "NOT_EQUAL":  Type.INT, 
            "AND":        Type.INT,    
            "OR":         Type.INT,     
        },
        Type.FLOAT: {
            "PLUS":       Type.FLOAT,
            "MINUS":      Type.FLOAT,
            "TIMES":      Type.FLOAT,
            "DIVIDE":     Type.FLOAT,
            "EQUALS":     Type.INT,
            "GREATER":    Type.INT,
            "LESS":       Type.INT,
            "LESS_EQ":    Type.INT,
            "GREATER_EQ": Type.INT,
            "IS_EQUAL":   Type.INT,
            "NOT_EQUAL":  Type.INT,
            "AND":        Type.INT,
            "OR":         Type.INT,
        },
        Type.STRING: {
            "PLUS":       Type.STRING,
            "MINUS":      Type.ERROR,
            "TIMES":      Type.STRING,
            "DIVIDE":     Type.ERROR,
            "EQUALS":     Type.ERROR,
            "GREATER":    Type.ERROR,
            "LESS":       Type.ERROR,
            "LESS_EQ":    Type.ERROR,
            "GREATER_EQ": Type.ERROR,
            "IS_EQUAL":   Type.INT,
            "NOT_EQUAL":  Type.INT,
            "AND":        Type.ERROR,
            "OR":         Type.ERROR,
        }
    },
    Type.FLOAT: {
        Type.INT:    {
            "PLUS":       Type.FLOAT,
            "MINUS":      Type.FLOAT,
            "TIMES":      Type.FLOAT,
            "DIVIDE":     Type.FLOAT,
            "EQUALS":     Type.FLOAT,
            "GREATER":    Type.INT,
            "LESS":       Type.INT,
            "LESS_EQ":    Type.INT,
            "GREATER_EQ": Type.INT,
            "IS_EQUAL":   Type.INT,
            "NOT_EQUAL":  Type.INT,
            "AND":        Type.INT,
            "OR":         Type.INT,
        },
        Type.FLOAT: {
            "PLUS":       Type.FLOAT,
            "MINUS":      Type.FLOAT,
            "TIMES":      Type.FLOAT,
            "DIVIDE":     Type.FLOAT,
            "EQUALS":     Type.FLOAT,
            "GREATER":    Type.INT,
            "LESS":       Type.INT,
            "LESS_EQ":    Type.INT,
            "GREATER_EQ": Type.INT,
            "IS_EQUAL":   Type.INT,
            "NOT_EQUAL":  Type.INT,
            "AND":        Type.INT,
            "OR":         Type.INT,
        },
        Type.STRING: {
            "PLUS":       Type.STRING,
            "MINUS":      Type.ERROR,
            "TIMES":      Type.ERROR,
            "DIVIDE":     Type.ERROR,
            "EQUALS":     Type.ERROR,
            "GREATER":    Type.ERROR,
            "LESS":       Type.ERROR,
            "LESS_EQ":    Type.ERROR,
            "GREATER_EQ": Type.ERROR,
            "IS_EQUAL":   Type.INT,
            "NOT_EQUAL":  Type.INT,
            "AND":        Type.ERROR,
            "OR":         Type.ERROR,
        },
    },
    Type.STRING: {
        Type.INT:    {
            "PLUS":       Type.STRING,
            "MINUS":      Type.ERROR,
            "TIMES":      Type.STRING,
            "DIVIDE":     Type.ERROR,
            "EQUALS":     Type.STRING,
            "GREATER":    Type.ERROR,
            "LESS":       Type.ERROR,
            "LESS_EQ":    Type.ERROR,
            "GREATER_EQ": Type.ERROR,
            "IS_EQUAL":   Type.INT,
            "NOT_EQUAL":  Type.INT,
            "AND":        Type.ERROR,
            "OR":         Type.ERROR,
        },
        Type.FLOAT: {
            "PLUS":       Type.STRING,
            "MINUS":      Type.ERROR,
            "TIMES":      Type.ERROR,
            "DIVIDE":     Type.ERROR,
            "EQUALS":     Type.STRING,
            "GREATER":    Type.ERROR,
            "LESS":       Type.ERROR,
            "LESS_EQ":    Type.ERROR,
            "GREATER_EQ": Type.ERROR,
            "IS_EQUAL":   Type.INT,
            "NOT_EQUAL":  Type.INT,
            "AND":        Type.ERROR,
            "OR":         Type.ERROR,
        },
        Type.STRING: {
            "PLUS":       Type.STRING,
            "MINUS":      Type.ERROR,
            "TIMES":      Type.ERROR,
            "DIVIDE":     Type.ERROR,
            "EQUALS":     Type.STRING,
            "GREATER":    Type.INT,
            "LESS":       Type.INT,
            "LESS_EQ":    Type.INT,
            "GREATER_EQ": Type.INT,
            "IS_EQUAL":   Type.INT,
            "NOT_EQUAL":  Type.INT,
            "AND":        Type.INT,
            "OR":         Type.INT,
        }, 
    },
}
