semantic_cube = {
    "int": {
        "int":    {
            "PLUS":       "int",  
            "MINUS":      "int",     
            "TIMES":      "int",    
            "DIVIDE":     "float",  
            "EQUALS":     "int", 
            "GREATER":    "int",   
            "LESS":       "int",    
            "LESS_EQ":    "int",    
            "GREATER_EQ": "int", 
            "IS_EQUAL":   "int",  
            "NOT_EQUAL":  "int", 
            "AND":        "int",    
            "OR":         "int",     
        },
        "float": {
            "PLUS":       "float",
            "MINUS":      "float",
            "TIMES":      "float",
            "DIVIDE":     "float",
            "EQUALS":     "int",
            "GREATER":    "int",
            "LESS":       "int",
            "LESS_EQ":    "int",
            "GREATER_EQ": "int",
            "IS_EQUAL":   "int",
            "NOT_EQUAL":  "int",
            "AND":        "int",
            "OR":         "int",
        },
        "string": {
            "PLUS":       "string",
            "MINUS":      "error",
            "TIMES":      "string",
            "DIVIDE":     "error",
            "EQUALS":     "error",
            "GREATER":    "error",
            "LESS":       "error",
            "LESS_EQ":    "error",
            "GREATER_EQ": "error",
            "IS_EQUAL":   "int",
            "NOT_EQUAL":  "int",
            "AND":        "error",
            "OR":         "error",
        }
    },
    "float": {
        "int":    {
            "PLUS":       "float",
            "MINUS":      "float",
            "TIMES":      "float",
            "DIVIDE":     "float",
            "EQUALS":     "float",
            "GREATER":    "int",
            "LESS":       "int",
            "LESS_EQ":    "int",
            "GREATER_EQ": "int",
            "IS_EQUAL":   "int",
            "NOT_EQUAL":  "int",
            "AND":        "int",
            "OR":         "int",
        },
        "float": {
            "PLUS":       "float",
            "MINUS":      "float",
            "TIMES":      "float",
            "DIVIDE":     "float",
            "EQUALS":     "float",
            "GREATER":    "int",
            "LESS":       "int",
            "LESS_EQ":    "int",
            "GREATER_EQ": "int",
            "IS_EQUAL":   "int",
            "NOT_EQUAL":  "int",
            "AND":        "int",
            "OR":         "int",
        },
        "string": {
            "PLUS":       "string",
            "MINUS":      "error",
            "TIMES":      "error",
            "DIVIDE":     "error",
            "EQUALS":     "error",
            "GREATER":    "error",
            "LESS":       "error",
            "LESS_EQ":    "error",
            "GREATER_EQ": "error",
            "IS_EQUAL":   "int",
            "NOT_EQUAL":  "int",
            "AND":        "error",
            "OR":         "error",
        },
    },
    "string": {
        "int":    {
            "PLUS":       "string",
            "MINUS":      "error",
            "TIMES":      "string",
            "DIVIDE":     "error",
            "EQUALS":     "string",
            "GREATER":    "error",
            "LESS":       "error",
            "LESS_EQ":    "error",
            "GREATER_EQ": "error",
            "IS_EQUAL":   "int",
            "NOT_EQUAL":  "int",
            "AND":        "error",
            "OR":         "error",
        },
        "float": {
            "PLUS":       "string",
            "MINUS":      "error",
            "TIMES":      "error",
            "DIVIDE":     "error",
            "EQUALS":     "string",
            "GREATER":    "error",
            "LESS":       "error",
            "LESS_EQ":    "error",
            "GREATER_EQ": "error",
            "IS_EQUAL":   "int",
            "NOT_EQUAL":  "int",
            "AND":        "error",
            "OR":         "error",
        },
        "string": {
            "PLUS":       "string",
            "MINUS":      "error",
            "TIMES":      "error",
            "DIVIDE":     "error",
            "EQUALS":     "string",
            "GREATER":    "int",
            "LESS":       "int",
            "LESS_EQ":    "int",
            "GREATER_EQ": "int",
            "IS_EQUAL":   "int",
            "NOT_EQUAL":  "int",
            "AND":        "int",
            "OR":         "int",
        }, 
    },
}
